# my-latex-renders task-readme-github-pages.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: my-latex-renders

outputs:
  - name: my-latex-renders-updated

run:
  path: ./my-latex-renders/ci/scripts/readme-github-pages.sh
  # args: [-debug]
